-- CreateTable
CREATE TABLE "TBLPARTNERSHIP" (
    "id" SERIAL NOT NULL,
    "tenantId" INTEGER NOT NULL,
    "supplierId" INTEGER NOT NULL,
    "retailId" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ativo',
    "validFrom" TIMESTAMP(3),
    "validTo" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPARTNERSHIP_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TBLPARTNERSHIP" ADD CONSTRAINT "TBLPARTNERSHIP_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TBLTENANT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPARTNERSHIP" ADD CONSTRAINT "TBLPARTNERSHIP_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "TBLFORN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPARTNERSHIP" ADD CONSTRAINT "TBLPARTNERSHIP_retailId_fkey" FOREIGN KEY ("retailId") REFERENCES "TBLRETAIL"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
