-- AlterTable
ALTER TABLE "TBLCAMPANHAITEM" ADD COLUMN     "productId" INTEGER;

-- AlterTable
ALTER TABLE "TBLJBPITEM" ADD COLUMN     "productId" INTEGER;

-- AlterTable
ALTER TABLE "TBLRETAILMEDIA_ITEM" ADD COLUMN     "productId" INTEGER;

-- CreateTable
CREATE TABLE "TBLPROD" (
    "id" SERIAL NOT NULL,
    "tenantId" INTEGER NOT NULL,
    "supplierId" INTEGER NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "complement" TEXT,
    "brand" TEXT,
    "category" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ativo',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLPROD_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TBLPROD_tenantId_code_key" ON "TBLPROD"("tenantId", "code");

-- AddForeignKey
ALTER TABLE "TBLPROD" ADD CONSTRAINT "TBLPROD_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TBLTENANT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLPROD" ADD CONSTRAINT "TBLPROD_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "TBLFORN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLJBPITEM" ADD CONSTRAINT "TBLJBPITEM_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPROD"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLCAMPANHAITEM" ADD CONSTRAINT "TBLCAMPANHAITEM_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPROD"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLRETAILMEDIA_ITEM" ADD CONSTRAINT "TBLRETAILMEDIA_ITEM_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPROD"("id") ON DELETE SET NULL ON UPDATE CASCADE;
