-- CreateTable
CREATE TABLE "TBLJBPITEM_MIX" (
    "id" SERIAL NOT NULL,
    "jbpItemId" INTEGER NOT NULL,
    "productId" INTEGER,
    "brandCriteria" TEXT,
    "categoryCriteria" TEXT,

    CONSTRAINT "TBLJBPITEM_MIX_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TBLJBPITEM_MIX" ADD CONSTRAINT "TBLJBPITEM_MIX_jbpItemId_fkey" FOREIGN KEY ("jbpItemId") REFERENCES "TBLJBPITEM"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLJBPITEM_MIX" ADD CONSTRAINT "TBLJBPITEM_MIX_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TBLPROD"("id") ON DELETE SET NULL ON UPDATE CASCADE;
