/*
  Warnings:

  - You are about to drop the `TBLUSER` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "TBLUSER";

-- CreateTable
CREATE TABLE "TBLCAMPANHA" (
    "id" SERIAL NOT NULL,
    "supplierId" INTEGER NOT NULL,
    "jbpId" INTEGER,
    "name" TEXT NOT NULL,
    "objective" TEXT,
    "channel" TEXT,
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'planejada',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLCAMPANHA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLCAMPANHAITEM" (
    "id" SERIAL NOT NULL,
    "campanhaId" INTEGER NOT NULL,
    "jbpItemId" INTEGER,
    "assetId" INTEGER NOT NULL,
    "title" TEXT,
    "contentType" TEXT,
    "artDeadline" TIMESTAMP(3),
    "approvalDeadline" TIMESTAMP(3),
    "goLiveDate" TIMESTAMP(3),
    "urlDestino" TEXT,
    "notes" TEXT,

    CONSTRAINT "TBLCAMPANHAITEM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLEXECPLANO" (
    "id" SERIAL NOT NULL,
    "supplierId" INTEGER NOT NULL,
    "jbpId" INTEGER,
    "name" TEXT NOT NULL,
    "periodStart" TIMESTAMP(3),
    "periodEnd" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'planejado',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLEXECPLANO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLEXECTAREFA" (
    "id" SERIAL NOT NULL,
    "planoExecId" INTEGER NOT NULL,
    "jbpItemId" INTEGER,
    "assetId" INTEGER NOT NULL,
    "storeScope" TEXT NOT NULL,
    "checklist" TEXT,
    "deadline" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'pendente',
    "photoUrl" TEXT,
    "notes" TEXT,

    CONSTRAINT "TBLEXECTAREFA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLRETAILMEDIA_PLANO" (
    "id" SERIAL NOT NULL,
    "supplierId" INTEGER NOT NULL,
    "jbpId" INTEGER,
    "name" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "periodStart" TIMESTAMP(3),
    "periodEnd" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'planejado',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TBLRETAILMEDIA_PLANO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLRETAILMEDIA_ITEM" (
    "id" SERIAL NOT NULL,
    "planoRetailId" INTEGER NOT NULL,
    "jbpItemId" INTEGER,
    "assetId" INTEGER NOT NULL,
    "pageType" TEXT,
    "position" TEXT,
    "device" TEXT,
    "impressionsTarget" INTEGER,
    "clicksTarget" INTEGER,
    "cpcNegociado" DOUBLE PRECISION,
    "totalValue" DOUBLE PRECISION,
    "notes" TEXT,

    CONSTRAINT "TBLRETAILMEDIA_ITEM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBLVENDASRESUMO" (
    "id" SERIAL NOT NULL,
    "supplierId" INTEGER NOT NULL,
    "jbpId" INTEGER,
    "ano" INTEGER NOT NULL,
    "mes" INTEGER NOT NULL,
    "channel" TEXT,
    "sellInValue" DOUBLE PRECISION,
    "sellOutValue" DOUBLE PRECISION,
    "volume" DOUBLE PRECISION,
    "marketShare" DOUBLE PRECISION,
    "notes" TEXT,

    CONSTRAINT "TBLVENDASRESUMO_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TBLCAMPANHA" ADD CONSTRAINT "TBLCAMPANHA_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "TBLFORN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLCAMPANHA" ADD CONSTRAINT "TBLCAMPANHA_jbpId_fkey" FOREIGN KEY ("jbpId") REFERENCES "TBLJBP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLCAMPANHAITEM" ADD CONSTRAINT "TBLCAMPANHAITEM_campanhaId_fkey" FOREIGN KEY ("campanhaId") REFERENCES "TBLCAMPANHA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLCAMPANHAITEM" ADD CONSTRAINT "TBLCAMPANHAITEM_jbpItemId_fkey" FOREIGN KEY ("jbpItemId") REFERENCES "TBLJBPITEM"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLCAMPANHAITEM" ADD CONSTRAINT "TBLCAMPANHAITEM_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "TBLATV"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLEXECPLANO" ADD CONSTRAINT "TBLEXECPLANO_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "TBLFORN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLEXECPLANO" ADD CONSTRAINT "TBLEXECPLANO_jbpId_fkey" FOREIGN KEY ("jbpId") REFERENCES "TBLJBP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLEXECTAREFA" ADD CONSTRAINT "TBLEXECTAREFA_planoExecId_fkey" FOREIGN KEY ("planoExecId") REFERENCES "TBLEXECPLANO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLEXECTAREFA" ADD CONSTRAINT "TBLEXECTAREFA_jbpItemId_fkey" FOREIGN KEY ("jbpItemId") REFERENCES "TBLJBPITEM"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLEXECTAREFA" ADD CONSTRAINT "TBLEXECTAREFA_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "TBLATV"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLRETAILMEDIA_PLANO" ADD CONSTRAINT "TBLRETAILMEDIA_PLANO_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "TBLFORN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLRETAILMEDIA_PLANO" ADD CONSTRAINT "TBLRETAILMEDIA_PLANO_jbpId_fkey" FOREIGN KEY ("jbpId") REFERENCES "TBLJBP"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLRETAILMEDIA_ITEM" ADD CONSTRAINT "TBLRETAILMEDIA_ITEM_planoRetailId_fkey" FOREIGN KEY ("planoRetailId") REFERENCES "TBLRETAILMEDIA_PLANO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLRETAILMEDIA_ITEM" ADD CONSTRAINT "TBLRETAILMEDIA_ITEM_jbpItemId_fkey" FOREIGN KEY ("jbpItemId") REFERENCES "TBLJBPITEM"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLRETAILMEDIA_ITEM" ADD CONSTRAINT "TBLRETAILMEDIA_ITEM_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "TBLATV"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLVENDASRESUMO" ADD CONSTRAINT "TBLVENDASRESUMO_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "TBLFORN"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBLVENDASRESUMO" ADD CONSTRAINT "TBLVENDASRESUMO_jbpId_fkey" FOREIGN KEY ("jbpId") REFERENCES "TBLJBP"("id") ON DELETE SET NULL ON UPDATE CASCADE;
